[package]
name = "launcher-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = "4.5.27"
crossterm = "0.28.1"
dirs = "6.0.0"
reqwest = { version = "0.12.12", features = ["blocking"] }
serde_json = "1.0.138"
